name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev xclip libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          sudo apt-get install -y openjdk-17-jdk unzip zip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build with Buildozer
        run: |
          yes | buildozer android debug
        env:
          ACCEPT_SHARED_SDK_LICENSE: 1

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-apk
          path: bin/*.apk
